version: '3.7'
services:
  app:
    build: .
    command: sleep infinity
    init: true
    ports:
      - "3000:3000"
      - "9229:9229"
    environment:
      - REDIS_HOST=redis
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - redis
  redis:
    image: redis